# Description: >
#   UdaPeople frontend stack.

# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String

# Resources:
#   WebsiteBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       ObjectOwnership: BucketOwnerEnforced
#       BucketName: !Sub "udapeople-${ID}"
      
#       WebsiteConfiguration:
#         IndexDocument: index.html
#         ErrorDocument: 404.html
      
#   WebsiteBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !Ref 'WebsiteBucket'
#       PolicyDocument:
#         Statement:
#         - Sid: PublicReadForGetBucketObjects
#           Effect: Allow
#           Principal: '*'
#           Action: s3:GetObject
#           Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

# Outputs:
#   WebsiteURL:
#     Value: !GetAtt WebsiteBucket.WebsiteURL
#     Description: URL for website hosted on S3

Description: >
  UdaPeople frontend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketName: !Sub "udapeople-${ID}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3
######################
